title: "Subhan Hassan"
name: "Subhan Hassan"
description: "Computer Engineering student at Virginia Tech."
url: https://subhanhassancodes.github.io
baseurl: ""
repository: "subhanhassancodes/subhanhassancodes.github.io"
